name: cat_app
description: Show Cat Pictures

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable:
  http: ^0.12.0+2
  json_annotation: ^2.0.0 

  flutter_bloc:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/loadingCat.gif
    - assets/loadingDog.gif
    - assets/loadingFox.gif
    - assets/confusedDog.gif

